apiVersion: v2
name: mybb
description: A Helm chart for Mybb
type: application
version: 0.1.0
appVersion: 1.8
maintainers:
  - name: hemachan
keywords:
  - mybb
home: https://github.com/Hemachandra-423/Mycharts/tree/main/Charts
sources:
  - https://github.com/mybb/docker
dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
  tags:
    - database